// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBF59zj72m4D1HXCSrII-D2COvjmti7k_M',
    appId: '1:879146065292:web:5a482745b7c5a80e138aa9',
    messagingSenderId: '879146065292',
    projectId: 'pokebuild-0',
    authDomain: 'pokebuild-0.firebaseapp.com',
    storageBucket: 'pokebuild-0.firebasestorage.app',
    measurementId: 'G-PCP67K8NPP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDURUm2pLPINGKcQmKmazzzlgNsHGUe_Uw',
    appId: '1:879146065292:android:f94a92866fd66d05138aa9',
    messagingSenderId: '879146065292',
    projectId: 'pokebuild-0',
    storageBucket: 'pokebuild-0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0sfEXsgXZcl8IRqokGdETBuibLCJtADM',
    appId: '1:879146065292:ios:e7fa356788c16421138aa9',
    messagingSenderId: '879146065292',
    projectId: 'pokebuild-0',
    storageBucket: 'pokebuild-0.firebasestorage.app',
    iosBundleId: 'com.example.pokemonTeamBuilder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0sfEXsgXZcl8IRqokGdETBuibLCJtADM',
    appId: '1:879146065292:ios:e7fa356788c16421138aa9',
    messagingSenderId: '879146065292',
    projectId: 'pokebuild-0',
    storageBucket: 'pokebuild-0.firebasestorage.app',
    iosBundleId: 'com.example.pokemonTeamBuilder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBF59zj72m4D1HXCSrII-D2COvjmti7k_M',
    appId: '1:879146065292:web:9994453fa71ecf41138aa9',
    messagingSenderId: '879146065292',
    projectId: 'pokebuild-0',
    authDomain: 'pokebuild-0.firebaseapp.com',
    storageBucket: 'pokebuild-0.firebasestorage.app',
    measurementId: 'G-8763GEZHLR',
  );
}
